"use strict";
exports.__esModule = true;
var express_1 = require("express");
var app = (0, express_1["default"])();
var PORT = 8080;
var database_mem_1 = require("./database-mem");
var data_ext_1 = require("./data-ext");
var services = require("./services")(database_mem_1["default"], data_ext_1["default"]);
var api = require("./api")(services);
app.use("/api", api);
app.listen(PORT);
